name: CV-X-IF v1.0.0-rc.1 Specification Public Review
description: Specification Public Review Comment for CV-X-IF v1.0.0-rc.1
title: "[Review Comment]: "
labels: ["public-review", "CV-X-IF-v1.0.0-rc.1"]
body:
  - type: markdown
    attributes:
      value: "Thanks for your review comment on the CV-X-IF v1.0.0-rc.1 specification! The PDF is at https://docs.openhwgroup.org/_/downloads/openhw-group-core-v-xif/en/v1.0.0-rc.1/pdf/. Please submit a separate issue for each comment."
#  - type: checkbox
#    attributes:
#      label: Is your employer an OpenHW Group member?
#      options:
#        - label: Yes
#        - label: No
  - type: dropdown
    attributes:
      label: Is your employer an OpenHW Group member?
      multiple: false
      options:
      - label: Yes
      - label: No
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comment
      description: Describe the comment, question, problem, or suggestion w.r.t. CV-X-IF v1.0.0-rc.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Resolution
      description: What changes to CV-X-IF v1.0.0-rc.1 do you recommend to address the comment?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Addition Info 
      description: Provide any additional information or links that relate to this comment
    validations:
      required: false